name: bigboss_eren
description: BigBoss Eren Kuyumculuk POS Sistemi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Temel Paketler (En Uyumlu Sürümler)
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  pdf: ^3.10.4
  printing: ^5.12.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 